// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCINj3HJI9nmji7Xy7fuLTldru1jCu8ksg',
    appId: '1:803306318523:web:a3b2bff05c57807ffc579e',
    messagingSenderId: '803306318523',
    projectId: 'ar-quest-e0a1a',
    authDomain: 'ar-quest-e0a1a.firebaseapp.com',
    storageBucket: 'ar-quest-e0a1a.firebasestorage.app',
    measurementId: 'G-K975WHJEQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7opqMzk7vcHJDSJeO2bQt5fJ4sTGpqIo',
    appId: '1:803306318523:android:9f320b6fa922e4cefc579e',
    messagingSenderId: '803306318523',
    projectId: 'ar-quest-e0a1a',
    storageBucket: 'ar-quest-e0a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBhCzek2pvpUcfSg8WYABnHTX74TwfQw',
    appId: '1:803306318523:ios:f692ee848100789afc579e',
    messagingSenderId: '803306318523',
    projectId: 'ar-quest-e0a1a',
    storageBucket: 'ar-quest-e0a1a.firebasestorage.app',
    iosBundleId: 'com.example.arquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVBhCzek2pvpUcfSg8WYABnHTX74TwfQw',
    appId: '1:803306318523:ios:f692ee848100789afc579e',
    messagingSenderId: '803306318523',
    projectId: 'ar-quest-e0a1a',
    storageBucket: 'ar-quest-e0a1a.firebasestorage.app',
    iosBundleId: 'com.example.arquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCINj3HJI9nmji7Xy7fuLTldru1jCu8ksg',
    appId: '1:803306318523:web:e2b9db12f37b92e3fc579e',
    messagingSenderId: '803306318523',
    projectId: 'ar-quest-e0a1a',
    authDomain: 'ar-quest-e0a1a.firebaseapp.com',
    storageBucket: 'ar-quest-e0a1a.firebasestorage.app',
    measurementId: 'G-4LZNVVYF2W',
  );
}
